Repository byh-association/broaden-agency, pull requests merged in 2022-12, with the labels that each got.

#23 Improve lighthouse score && fill with real …
  public/landing/great-car-preview.png
  src/component/advantages-section/data.ts
  src/component/header/header-menu.tsx
  src/component/header/header-navigation.tsx
  src/component/hero-section/hero-section.astro
  src/component/service-section/data.ts
  src/component/service-section/service-card.astro
  src/component/showcase-card/showcard-wrapper.astro
  src/component/showcase-card/showcase-card.astro
  src/pages/index.astro
  src/pages/showcases.astro
Labels: ⭐ feature

#25 Implement Estimation step 🧮
  .env.example
  .eslintrc.json
  astro.config.mjs
  package.json
  public/calculator/api_illustration.svg
  public/calculator/design_illustration.svg
  public/calculator/landing_page_illustration.svg
  public/calculator/marketing_illustration.svg
  public/calculator/mobile_application_illustration.svg
  public/calculator/quiz_illustration.svg
  public/calculator/success_illustration.svg
  public/calculator/web_application_illustration.svg
  public/icons/arrow-right-light.svg
  public/icons/cursor-click.svg
  public/icons/error.svg
  public/icons/minus.svg
  public/icons/plus.svg
  public/logos/dark.svg
  public/logos/light.svg
  src/component/calculator/components/boolean-form.tsx
  src/component/calculator/components/calculator-service-card.tsx
  src/component/calculator/components/cart-item.tsx
  src/component/calculator/components/cart.tsx
  src/component/calculator/components/counter-form.tsx
  src/component/calculator/data/data.ts
  src/component/calculator/data/prices.json
  src/component/calculator/hooks/use-cart-price.tsx
  src/component/calculator/index.tsx
  src/component/calculator/steps/contact.tsx
  src/component/calculator/steps/questions.tsx
  src/component/calculator/steps/services.tsx
  src/component/calculator/steps/success.tsx
  src/component/contact-section/contact-section.astro
  src/component/container.astro
  src/component/footer/footer.astro
  src/component/header/header-menu.tsx
  src/component/header/header-navigation.tsx
  src/component/header/header.astro
  src/component/header/helpers/get-header-color-scheme.ts
  src/component/hero-section/hero-section.astro
  src/component/hero-section/rotating-text.astro
  src/component/input/index.tsx
  src/component/radio-button/index.tsx
  src/component/review-section/review-section-carousel.tsx
  src/component/service-section/service-card.astro
  src/component/textarea/index.tsx
  src/layouts/landing-layout.astro
  src/layouts/landing-section-layout.astro
  src/mails/cart-summary.tsx
  src/pages/api/send-cart-summary.json.ts
  src/pages/estimate.astro
  src/styles/globals.css
  src/utils/mailer.ts
  tsconfig.json
  yarn.lock
Labels: ⭐ feature, 🏗️ dependency, 📘 configuration

#27 Implement cart summary email for client and company 🛒
  package.json
  public/icons/default-twitter.png
  public/icons/facebook-default.png
  public/icons/instagram-default.png
  public/icons/linkedin-default.png
  public/logos/light.png
  src/component/calculator/components/cart-item.tsx
  src/component/calculator/components/cart.tsx
  src/component/calculator/hooks/use-cart-price.tsx
  src/config.ts
  src/mails/cart-summary-client.hbs
  src/mails/cart-summary-company.hbs
  src/mails/cart-summary.tsx
  src/pages/api/send-cart-summary.json.ts
  src/utils/mailer.ts
  yarn.lock
Labels: ⭐ feature, 🏗️ dependency

#24 Implement meta tags, description, title for pages 🧠
  src/layouts/landing-layout.astro
  src/pages/estimate.astro
  src/pages/index.astro
  src/pages/showcases.astro
Labels: ⭐ feature
