Repository byh-association/broaden-agency, pull requests merged in 2022-11, with the labels that each got.

#2 Implement base styles and logic 🎨
  .husky/pre-commit
  package.json
  src/components/container.tsx
  src/env/schema.mjs
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/styles/globals.css
  tailwind.config.cjs
  yarn.lock
Labels: ⭐ feature, 🏗️ dependency

#3 Move pages folder to the app folder 😶‍🌫️
  .gitignore
  next.config.mjs
  src/app/(landing)/head.tsx
  src/app/(landing)/layout.tsx
  src/app/(landing)/page.tsx
  src/app/components/container.tsx
  src/app/layout.tsx
  src/app/providers/index.tsx
  src/app/providers/trpc-provider.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/utils/trpc.ts
  tsconfig.json
Labels: 📘 configuration

#4 Configure auto import sort and TS paths 📘
  .eslintrc.json
  package.json
  src/app/components/container.tsx
  src/env/server.mjs
  src/pages/api/auth/[...nextauth].ts
  src/server/common/get-server-auth-session.ts
  src/server/trpc/router/_app.ts
  src/server/trpc/router/auth.ts
  src/server/trpc/router/example.ts
  tsconfig.json
  yarn.lock
Labels: 🏗️ dependency, 📘 configuration

#5 Implement landing footer 🧱
  .husky/pre-commit
  next.config.mjs
  package.json
  src/app/(landing)/components/footer/index.tsx
  src/app/(landing)/components/footer/link.tsx
  src/app/(landing)/layout.tsx
  src/app/layout.tsx
  src/app/providers/index.tsx
  src/app/providers/trpc-provider.tsx
  src/assets/icons/facebook.svg
  src/assets/icons/instagram.svg
  src/assets/icons/linkedin.svg
  src/assets/icons/twitter.svg
  tsconfig.json
  yarn.lock
Labels: ⭐ feature, 🏗️ dependency, 📘 configuration

#7 Implement base Header component
  package.json
  src/app/(landing)/components/header/header-navigation-menu.tsx
  src/app/(landing)/components/header/index.tsx
  src/app/(landing)/layout.tsx
  src/styles/globals.css
  yarn.lock
Labels: ⭐ feature, 🏗️ dependency

#8 Get back to the pages folder instead of app folder 😁
  next.config.mjs
  src/app/(landing)/components/header/index.tsx
  src/app/(landing)/head.tsx
  src/app/(landing)/layout.tsx
  src/app/(landing)/page.tsx
  src/app/layout.tsx
  src/app/providers/index.tsx
  src/app/providers/trpc-provider.tsx
  src/components/container.tsx
  src/components/footer/index.tsx
  src/components/footer/link.tsx
  src/components/header/header-navigation-menu.tsx
  src/components/header/index.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/index.tsx
  src/utils/trpc.ts
Labels: 📘 configuration

#9 Implement service section 🐕‍🦺
  public/icons/google.svg
  public/icons/shopify.svg
  public/icons/sketch.svg
  public/icons/vs-code.svg
  src/components/header/header-navigation-menu.tsx
  src/components/service-section/data.ts
  src/components/service-section/index.tsx
  src/components/service-section/service-card.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ⭐ feature

#11 Implement contact section
  src/components/contant-section/index.tsx
  src/components/hero-section.tsx
  src/components/rotating-text.tsx
  src/pages/index.tsx
  tailwind.config.cjs
Labels: ⭐ feature

#10 Implement landing review section 👨‍👩‍👧‍👦
  next.config.mjs
  src/components/hero-section.tsx
  src/components/review-card.tsx
  src/components/review-section.tsx
  src/components/rotating-text.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ⭐ feature

#12 Update header layout according to design
  src/component/header/header.astro
  src/layouts/landing-layout.astro
  src/styles/globals.css
Labels: ⭐ feature

#14 Update footer layout
  public/icons/default-facebook.svg
  public/icons/default-google.svg
  public/icons/default-instagram.svg
  public/icons/default-linkedin.svg
  public/icons/white-facebook.svg
  public/icons/white-instagram.svg
  public/icons/white-linkedin.svg
  public/icons/white-twitter.svg
  src/component/contact-section/contact-section.astro
  src/component/footer/footer-link.astro
  src/component/footer/footer.astro
  src/component/header/header.astro
  src/layouts/landing-layout.astro
  src/pages/index.astro
  src/styles/globals.css
Labels: ⭐ feature

#13 Implement advantages section 👗
  package.json
  public/landing/calendar.svg
  public/landing/charts.svg
  public/landing/rocket.svg
  src/component/advantages-section/advantage-card.type.ts
  src/component/advantages-section/advantages-card.astro
  src/component/advantages-section/advantages-section.astro
  src/component/advantages-section/data.ts
  src/component/review-section/review-section.astro
  src/component/service-section/service-section.astro
  src/layouts/landing-section-layout.astro
  src/pages/index.astro
  src/styles/globals.css
Labels: ⭐ feature

#16 Change service section according to design
  public/icons/design.svg
  public/icons/google.svg
  public/icons/marketing.svg
  public/icons/shopify.svg
  public/icons/sketch.svg
  public/icons/vs-code.svg
  public/icons/web-development.svg
  src/component/service-section/data.ts
  src/component/service-section/service-card.astro
  src/component/service-section/service-card.tsx
  src/component/service-section/service-card.type.ts
  src/component/service-section/service-section-content.tsx
  src/component/service-section/service-section.astro
  src/styles/globals.css
Labels: ⭐ feature

#17 Fix Hero section rotating in Firefox
  src/component/hero-section/rotating-text.astro
  tailwind.config.cjs
Labels: 🪱 bug

#18 Remove icon button from header ✈️
  src/component/header/header.astro
Labels: ⭐ feature

#19 Update small parts of layout by new design requirements 🌇
  src/component/advantages-section/advantages-card.astro
  src/component/advantages-section/advantages-section.astro
  src/component/service-section/service-card.astro
  src/pages/index.astro
Labels: ⭐ feature

#20 Implement showcase page
  public/icons/default-twitter.svg
  src/component/contact-section/contact-section.astro
  src/component/header/header.astro
  src/component/hero-section/hero-section.astro
  src/component/showcase-card/showcase-card.astro
  src/layouts/landing-layout.astro
  src/pages/index.astro
  src/pages/showcases.astro
Labels: ⭐ feature

#21 Implement header mobile menu
  src/component/header/header-menu.tsx
  src/component/header/header-navigation.tsx
  src/component/header/header.astro
  src/component/header/helpers/get-header-color-scheme.ts
  src/component/hero-section/rotating-text.astro
Labels: ⭐ feature
